spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: 'true'
        show_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MariaDBDialect
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    password: '1234'
    username: minbae
    url: jdbc:mariadb://1.201.141.79:3306/minbae?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul;
  profiles:
    include: oauth0p;
  data:
    rest:
      basePath: /api
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.minbae.user.domain
server:
  port: '9090'
